[cursor.style]
shape = "underline"

[font]
size = 7.0

[font.bold]
family = "Jetbrainsmonoextrabold Nerd Font Mono"
style = "Bold"

[font.italic]
family = "Jetbrainsmono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "Jetbrainsmono Nerd Font Mono"
style = "Regular"

[shell]
program = "/bin/zsh"

[window]
opacity = 0.7
