[colors.primary]
background = "#232925"
foreground = "#B0F1CA"

[colors.cursor]
text = "#232925"
cursor = "#B0F1CA"

[colors.normal]
black   = "#484E4B"
red     = "#0D2D1E"
green   = "#2E3886"
yellow  = "#B2453B"
blue    = "#6297A3"
magenta = "#DBB267"
cyan    = "#1ED867"
white   = "#86E3AB"

[colors.bright]
black   = "#5E9F77"
red     = "#0D2D1E"
green   = "#2E3886"
yellow  = "#B2453B"
blue    = "#6297A3"
magenta = "#DBB267"
cyan    = "#1ED867"
white   = "#86E3AB"