[cursor.style]
shape = "underline"

[font]
size = 10

[font.bold]
family = "Monospace"
style = "Bold"

[font.italic]
family = "Monospace"
style = "Italic"

[font.normal]
family = "Monospace"
style = "Regular"

[terminal.shell]
program = "zellij"

[window]
opacity = 0.7

[terminal]
